name: find-my-yaml

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'output/**'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out main repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Checkout yamlfinder
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: jinopl/yamlfinder
        path: tools
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: pip install argparse datetime

    - name: Run yaml finder
      run: | 
        python3 yamlfinder.py
      working-directory: ./tools/

    - name: Remove tool folders
      run: rm -rf tools

    # - name: Check if there are any changes
    #   id: verify_diff
    #   run: |
    #     git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    # - name: Commit and push if there is changes
    #   if: steps.verify_diff.outputs.changed == 'true'
    #   run: |
    #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config --local user.name "github-actions"
    #     git status
    #     git add .
    #     git commit -m "Adding outputfile by github actions"
    #     git push
    
