name: find-my-yaml

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'output/**'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out main repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Checkout yamlfinder
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: jinopl/yamlfinder
        path: tools
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: pip install argparse datetime

    - name: Run yaml finder
      run: | 
        python3 yamlfinder.py --ifile ../filenames.txt --ofile outputfile.txt
        mv outputfile.txt ../
      working-directory: ./tools/

    - name: Remove tool folders
      run: rm -rf tools

    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: my-output
    #     path: ./outputfile.txt

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: my-output

    - name: Display the file
      run: ls -la
    
    - name: Display the file
      run: cat ./outputfile.txt